### ISSUE TITLE
Video oynatıcı için not sistemi

### ISSUE THREAD

**Issue by mkutlu** [amdetu/streama#1]
Programda kullanıcıların video izlerken veya direkt videolara yönelik not tutabilmesini sağlayan bir çalışma hedeflenmektedir. 
Kullanıcı video player ile izleme esnasında atanacak bir kısayol tuşu veya arayüzde eklenecek bir buton ile not alma işlemini gerçekleştirebilecek.
Not kısmında video izleniyorsa durdurarak zaman bilgisi eklenerek belirli karakter uzunluğu dahilinde ekleme yapılacak. Kullanıcı ayrıca opsiyonel olarak 
bu notu gizli veya açık hale getirebilecek. Bu not kayıtları eşzamanlı olarak veritabanına bağlı olduğu bilgiler ile birlikte gönderilecek. Tutulan bu
veriler arama kısmında ayrıca bulunabilir hale getirilecek. Bu çalışma zamanla kodun imkanları dahilinde şekillenebilir.

**Comment by cagdasgerede** [comment]
Description 700 karakterdan az. Ya tekrar düzenleyiniz ya da bir issue daha yaratınız.

**Comment by mkutlu** [comment]
Açıklama karakter sınırları dahilinde düzenlenmiştir.

**Comment by cagdasgerede** [comment]
Ok
